### ISSUE TITLE
Breaking Changes Tracking Issue

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#42]
These are ideas I had for changes, but they would be breaking changes, so need discussion.
- [x] Remove `EventType` from `InputEvent` - it seems redundant with `EventCode`, as `match`ing on `EventCode` has the same capabilities
- [x] Remove `Device::new()`, favoring `Device::new_from_fd()` making a properly initialized file be an invariant of `Device`. (Also remove `Device::set_fd()`)
- [x] Rename functions called *fd, but which operate on `Files` to *file, as `RawFd`s are different from `File`s and the current name is confusing.
    - [x] `Device::new_from_fd()` to `Device::new_from_file()`
    - [x] `Device::change_fd()` to `Device::change_file()`
- [x] Replace `Device::fd(&self) -> Option<File>` and `UinputDevice::fd(&self) -> Option<File>` with `Device::into_fd(self) -> RawFd` and `UinputDevice::into_fd(self) -> RawFd`. As they currently stand, these functions are unsafe - dropping the returned file, then operating on the `Device` causes writing to `free`d memory.
- [x] change `pub struct TimeVal {pub tv_sec: c_long, pub tv_usec: c_long,}` to `pub struct TimeVal {pub tv_sec: time_t, pub tv_usec: suseconds_t}`. (on some linux platforms, like sparc64, `pub type suseconds_t = i32;`)
- [x] make `struct TimeVal` fields non-`pub`, make the `new` method check that `tv_usec` is within the proper range. Overall make that `tv_usec` < 10^6 an invariant of `TimeVal`).
- [x] make `enable` generic over `EventType`, `EventCode` and `InputProp`

Scrapped
- [X] ~Hide compiling libevdev from source behind non-default feature flag~

**Comment by ndesh26** [comment]
The reason for having most of this functions around it to maintain compatibility with libevdev. This allows libevdev users an easier transition to evdev-rs. 

* As I mentioned before as well I want to stick to the behaviour followed by the other rust bindings. And there are multiple libs that build the source library from scratch (if not available) by default. Examples are [git2-rs](https://github.com/alexcrichton/git2-rs) and [curl-rust](https://github.com/alexcrichton/curl-rust) which are maintained by a core member from the rust team. I do want to print a warning message in the case when we built from source but I haven't been able to find a way to do that. 

* The `EventCode` enum carries more information as compared to the corresponding `event_code` enum in libevdev. The reason for this redundancy was to harness the powerful features of Rust enums to ensure that only certain event code types are allowed with a particular event type. And that's how `EventType` became redundant. However I would like to keep `EventType` as it a core part of libevdev.
 
* There could be Devices which are not associated with a file. This is used e.g. when we want to create a uinput device. 
```
let mut dev = Device::new().unwrap();
dev.enable(EventCode::EV_KEY(EV_KEY::KEY_RESERVED));

let mut udev = UInputDevice::create_from_device(dev);
```

* Regarding the use of fd in function names, I think we should shift to using file since we not using fd anymore. But since these functions are part of a very common work flow, I would like to deprecate them first and then remove them in subsequent releases.  

* We need to address issue like the one caused by `Device::fd(&self) -> Option<File>`. I would like to avoid exposing `RawFd` to the users. Do you think there is a way to keep using `File`?

**Comment by maxbla** [comment]
Lets delay the discussion of my point on compiling libevdev from source. I'll ask the various maintainers why they do it that way.

What if `EventType` was a function on `InputEvent` instead of a field? Then we get compatibility with libevdev, and don't have to pay the storage penalty for storing the field separately.

> There could be Devices which are not associated with a file.

This is particularly problematic for my goal. I just want the type system to reflect whether the device is initialized or not. We could have two device types - an uninitialized device type and an initialized device type, but this seems pretty complicated. I'm at a bit of a dead end for rustifying this API. At the very least we could write in the documentation that you should prefer `Device::new_from_fd()`

> I would like to deprecate them first and then remove them in subsequent releases.

Yeah, this sounds good to me. We should introduce the new ones with new names, deprecate the old ones, then wait a few releases.

> Do you think there is a way to keep using File?

I mispoke in my checklist above. I think we have a few options here.
1. `Device::into_file(self) -> Option<File>` - consume device, turn it into a file
2. `Device::as_file<'a>(&'a mut self) -> Option<&'a File>` - give a file temporarily, so long as the device does not need to be used. This file is owned by the Device, so when it goes out of scope, it is not closed.
3. `Device::as_fd(&self) -> Option<RawFd>` - give out the underlying fd to the device without thinking. If a user closes this somehow, everything breaks.

I don't like the third option because the user will probably just use the RawFd to create a File and we'll be in the same mess we started in, only with more lines of user code. I think both 1 and 2 are worth a try.

**Comment by maxbla** [comment]
There's another breaking change that I want to make. I'd like to change the signature of `enable` from
```rust
pub fn enable(&self, blob: &dyn Any) -> Result<()>
```
to
```rust
pub fn<T:Enable> enable(&self, blob: &T) -> Result<()>
```
Where Enable is a trait that all of `EventType`, `EventCode` and `InputProp` implement. I want to make this change, because `Any` is a code smell in Rust. Use of `Any` allows errors that could be caught at compile time to happen at run time.

**Comment by ndesh26** [comment]
We can finally close this issue. Thanks for all the effort @maxbla!!
